#include "pal_time.h"
#include "stm32f411xe.h"

/*
 * V0 configuration
 *
 * Assumption:
 * Processor clock = 16 MHz
 *
 * 16,000,000 cycles / second
 *        =
 * 16,000 cycles / millisecond
 *
 * SysTick RELOAD = N - 1
 */
#define PAL_TIME_CPU_HZ       16000000U
#define PAL_TIME_TICK_HZ      1000U
#define PAL_TIME_RELOAD       ((PAL_TIME_CPU_HZ / PAL_TIME_TICK_HZ) - 1U)

/*
 * System time in milliseconds.
 *
 * Incremented by SysTick_Handler() every 1 ms.
 */
static volatile uint32_t system_ms = 0U;


/*
 * Initialize SysTick for a 1 ms system tick.
 */
void PAL_Time_Init(void)
{
    /*
     * 1. Program reload value.
     */
    SysTick->LOAD = PAL_TIME_RELOAD;

    /*
     * 2. Clear current counter and COUNTFLAG.
     */
    SysTick->VAL = 0U;

    /*
     * 3. Configure and enable SysTick.
     *
     * CLKSOURCE = 1 -> processor clock
     * TICKINT   = 1 -> enable SysTick interrupt
     * ENABLE    = 1 -> enable counter
     */
    SysTick->CTRL = (1U << 2) |
                    (1U << 1) |
                    (1U << 0);

    /*
     * Start system time from zero.
     */
    system_ms = 0U;
}


/*
 * SysTick interrupt handler.
 *
 * Called every 1 ms.
 */
void SysTick_Handler(void)
{
    system_ms++;
}


/*
 * Return elapsed system time in milliseconds.
 */
uint32_t PAL_Time_GetMs(void)
{
    return system_ms;
}


/*
 * Blocking delay in milliseconds.
 *
 * Uses the system time generated by SysTick.
 */
void PAL_Time_DelayMs(uint32_t ms)
{
    uint32_t start = PAL_Time_GetMs();

    while ((PAL_Time_GetMs() - start) < ms)
    {
        /*
         * Wait.
         *
         * SysTick continues running and updates
         * system_ms through its interrupt.
         */
    }
}
